version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: "docker-mongodb"
    env_file:
      - .env
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    # depends_on:
    #   - mongodb
    container_name: "docker-mongo-express"
    env_file:
      - .env_ex
    restart: always
