version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: "docker-mongodb"
    env_file:
      - .env
